# Generated by Django 3.2.3 on 2021-07-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=0)),
                ('payment_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('email', models.EmailField(max_length=1000)),
                ('number', models.CharField(max_length=10)),
                ('anonymous', models.BooleanField(default=False)),
                ('amount', models.FloatField(max_length=100000)),
                ('paid', models.BooleanField(default=False)),
                ('receipt', models.BooleanField(default=False)),
            ],
        ),
    ]
